USE smoothies;
CREATE TABLE TBCLIENTS(
	ID VARCHAR(20),
    NAME VARCHAR(150),
    ADDRESS1 VARCHAR(150),
    ADDRESS2 VARCHAR(150),
    DISTRICT VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    POSTAL_CODE VARCHAR(10),
    AGE SMALLINT,
    SEX VARCHAR(1),
    CREDIT_LINE FLOAT,
    PURCHASE_VOLUME FLOAT,
    FIRST_PURCHASE BIT
);

-- From wizard
CREATE TABLE `smoothies`.`tbproducts` (
  `product` VARCHAR(20) NULL,
  `name` VARCHAR(150) NULL,
  `container` VARCHAR(50) NULL,
  `volume` VARCHAR(20) NULL,
  `flavor` VARCHAR(50) NULL,
  `price` FLOAT NULL);

CREATE TABLE TBSALESPEOPLE (
	ID varchar(5),
    NAME varchar(100),
    COMMISSION_PERCENT float);

DROP TABLE TBSALESPEOPLE;